version: '3.9'

services:
  users-api-staging:
    restart: always
    build: .
    ports:
    - 3403:3003
    environment:
      NODE_ENV: development
      DB_USERNAME: __DB_USERNAME__
      DB_PASSWORD: __DB_PASSWORD__
      DB_HOST: __DB_HOST__
      JWT_SECRET: __JWT_SECRET__
      DB_PORT: __DB_PORT__
